# Site Settings
site_name: 微风拂过之处
site_url: https://liuyihao.github.io/
site_author: 刘怡豪

# Document Settings
nav:
  - 主页: 'index.md'

# Theme Settings
theme:
  name: material
  language: zh
  custom_dir: custom_theme/

