# Site Settings
site_name: 微风拂过之处
site_url: https://liuyihao.github.io/starry/
site_author: 刘怡豪

# Watch Settings
watch:
  - custom_theme/
  - scripts/

# Document Settings
nav:
  - 主页: 'index.md'
  - 日本語の勉強:
    - 'japanese/index.md'
    - 五十音: 'japanese/gojyuon.md'
    - 文法: 
      - 'japanese/bunpou/index.md'
      - 用言:
        - 动词: 
          - 概述: 'japanese/bunpou/doushi.md'
          - 动词未然形: 'japanese/bunpou/doushi1.md'  
          - 动词（第一）连用形: 'japanese/bunpou/doushi2.md' 
          - 动词（第二）连用形: 'japanese/bunpou/doushi3.md' 
          - 动词终止形: 'japanese/bunpou/doushi4.md'
          - 动词连体形: 'japanese/bunpou/doushi5.md'
          - 动词假定形: 'japanese/bunpou/doushi6.md'
          - 动词命令形: 'japanese/bunpou/doushi7.md'
          - 动词推量形: 'japanese/bunpou/doushi8.md'
          - 可能动词: 'japanese/bunpou/doushi9.md'
          - 授受动词: 'japanese/bunpou/doushi10.md'
          - 敬语动词: 'japanese/bunpou/doushi11.md'
        - 形容词: 'japanese/bunpou/keiyoushi.md'
        - 形容动词: 'japanese/bunpou/keiyoudoushi.md'
      - 附属词: 
        - 助词:
          - 格助词: 'japanese/bunpou/kakujyoshi.md'
          - 终助词: 'japanese/bunpou/shuujyoshi.md'
          - 副助词: 'japanese/bunpou/fukujyoshi.md'
          - 接续助词: 'japanese/bunpou/setsuzokujyoshi.md'
    - ごちうさ: 'japanese/gochiusa.md'
  - 知识分享: 
    - 'tutorials/index.md'
    - SSH密钥的使用: 'tutorials/ssh_keys.md'
    - 程序员演奏音乐: 'tutorials/music.md'
  - 小工具: 
    - 'tools/index.md'
    - 抽签: 'tools/draw.md'
    - 今天吃什么食堂: 'tools/canteen.md'

# Markdown
markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.arithmatex:
      generic: true

# Extra CSS and JS
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Hooks
hooks:
  - scripts/pre_process_japanese.py

# Theme Settings
theme:
  name: material
  language: zh
  custom_dir: custom_theme/
  # Color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Logo and Icon
  logo: assets/images/sun.svg
  favicon: assets/images/favicon.ico
  # Features
  features:
    # - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top        

# Extra Parameters
extra:
  homepage: '../'


