# Site Settings
site_name: 微风拂过之处
site_url: https://liuyihao.github.io/starry/
site_author: 刘怡豪

# Watch Settings
watch:
  - custom_theme/
  - scripts/

# Document Settings
nav:
  - 主页: 'index.md'
  - 日本語の勉強:
    - 'japanese/index.md'
    - 五十音: 
      - 五十音: 'japanese/gojyuon/index.md'
    - 语法: 
      - 语法: 'japanese/bunpou/index.md'
      - 体言:
        - 代词: 'japanese/bunpou/taigen/taigen1.md'
        - 数量词: 'japanese/bunpou/taigen/taigen2.md'
        - 形式体言: 'japanese/bunpou/taigen/taigen3.md'
        - 常用的体言: 'japanese/bunpou/taigen/taigen4.md'
      - 用言:
        - 动词: 
          - 概述: 'japanese/bunpou/doushi/doushi.md'
          - 动词未然形: 'japanese/bunpou/doushi/doushi1.md'  
          - 动词（第一）连用形: 'japanese/bunpou/doushi/doushi2.md' 
          - 动词（第二）连用形: 'japanese/bunpou/doushi/doushi3.md' 
          - 动词终止形: 'japanese/bunpou/doushi/doushi4.md'
          - 动词连体形: 'japanese/bunpou/doushi/doushi5.md'
          - 动词假定形: 'japanese/bunpou/doushi/doushi6.md'
          - 动词命令形: 'japanese/bunpou/doushi/doushi7.md'
          - 动词推量形: 'japanese/bunpou/doushi/doushi8.md'
          - 可能动词: 'japanese/bunpou/doushi/doushi9.md'
          - 授受动词: 'japanese/bunpou/doushi/doushi10.md'
          - 敬语动词: 'japanese/bunpou/doushi/doushi11.md'
        - 形容词: 'japanese/bunpou/keiyoushi.md'
        - 形容动词: 'japanese/bunpou/keiyoudoushi.md'
      - 附属词: 
        - 助词:
          - 格助词: 'japanese/bunpou/jyoushi/kakujyoshi.md'
          - 终助词: 'japanese/bunpou/jyoushi/shuujyoshi.md'
          - 副助词: 'japanese/bunpou/jyoushi/fukujyoshi.md'
          - 接续助词: 'japanese/bunpou/jyoushi/setsuzokujyoshi.md'
        - 助动词: 'japanese/bunpou/jyodoushi.md'
      - 文体: 
        - 敬体与简体: 'japanese/bunpou/buntai/buntai1.md'
        - 接头词: 'japanese/bunpou/buntai/buntai2.md'
        - 接尾词: 'japanese/bunpou/buntai/buntai3.md'
        - 其他: 'japanese/bunpou/buntai/buntai4.md'
    - 句型: 
      - 句型: 'japanese/bunkei/index.md'
      - 一般句型: 'japanese/bunkei/1.md'
      - 比较句型: 'japanese/bunkei/2.md'
      - 敬语句型: 'japanese/bunkei/3.md'
      - 五十音分类: 
        - あ行: 'japanese/bunkei/a.md'
        - か行: 'japanese/bunkei/ka.md'
        - さ行: 'japanese/bunkei/sa.md'
        - た行: 'japanese/bunkei/ta.md'
        - な行: 'japanese/bunkei/na.md'
        - は行: 'japanese/bunkei/ha.md'
        - ま行: 'japanese/bunkei/ma.md'
        - や行: 'japanese/bunkei/ya.md'
    - ごちうさ: 
      - 点兔: 'japanese/gochiusa/index.md'
  - 编程:
    - 'program/index.md'
    - Haskell: 
      - 'program/haskell/index.md'
      - IO模块: 'program/haskell/io.md'
      - 队列: 'program/haskell/queue.md'
      - 栈: 'program/haskell/stack.md'
      - 树: 'program/haskell/tree.md'
      - LeetCode:
        - 2529: 'program/haskell/leetcode/2529.md'
  - 知识分享: 
    - 'tutorials/index.md'
    - SSH密钥的使用: 'tutorials/ssh_keys.md'
    - 程序员演奏音乐: 'tutorials/music.md'
  - 小工具: 
    - 'tools/index.md'
    - 抽签: 'tools/draw.md'
    - 今天吃什么食堂: 'tools/canteen.md'
  - 图库:
    - 'images/index.md'
    - 少女乐队哭泣: 'images/gbc/index.md'

# Markdown
markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: Anchor link to this section for reference
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.arithmatex:
      generic: true

# Extra CSS and JS
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Hooks
hooks:
  - scripts/pre_process_japanese.py

# Theme Settings
theme:
  name: material
  language: zh
  custom_dir: custom_theme/
  # Color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Logo and Icon
  logo: assets/images/sun.svg
  favicon: assets/images/favicon.ico
  # Features
  features:
    # - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top        

# Extra Parameters
extra:
  homepage: '../'


