# Site Settings
site_name: 微风拂过之处
site_url: https://liuyihao.github.io/starry/
site_author: 刘怡豪

# Watch Settings
watch:
  - custom_theme/

# Document Settings
nav:
  - 主页: 'index.md'
  - 小工具: 
    - 抽签: 'tools/draw.md'
    - 今天吃什么食堂: 'tools/tsinghua_draw.md'

# Theme Settings
theme:
  name: material
  language: zh
  custom_dir: custom_theme/
  # Color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Logo and Icon
  logo: assets/images/sun.svg
  favicon: assets/images/favicon.ico
  # Features
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top

# Extra Parameters
extra:
  homepage: '../'


